### ISSUE TITLE
Cannot read log inside subdirectory ( eg /var/log/apache2/access.log )

### ISSUE THREAD

**Issue by AndyNewmanCRIBL** [lmnewton/log-exporter#1]
404 not found when reading a log inside a subdirectory

```bash
curl --location 'http://localhost:8000/logs/apache2/access.log?page=1&lines_to_read=2&size=50'
```

INFO:     172.20.0.1:52080 - "GET /logs/apache2/access.log?page=1&lines_to_read=2&size=50 HTTP/1.1" 404 Not Found

**Comment by lmnewton** [comment]
Good find! Thanks. See the linked PR #6 for the fixes here.

Here I decided to go with the supported `path` designation with FastAPI for the cleanest solution instead `urllib.parse` which would work but letting the framework handle this here seems clean as FastAPI already handles some validation.
