### ISSUE TITLE
READ_LOCATION envvar not setting location used in docker compose

### ISSUE THREAD

**Issue by AndyNewmanCRIBL** [lmnewton/log-exporter#2]
When running in docker-compose, the  READ_LOCATION env var is not used to set the host system location to use

https://github.com/lmnewton/log-exporter/blob/main/docker-compose.yml#L4C7-L4C20
`      READ_LOCATION: "/logs"
`
but the volume to mount is hardcoded to /var/log
  volumes:
`      - /var/log/:/logs:ro`
instead of  the READ_LOCATION

**Comment by lmnewton** [comment]
In this case that environment variable is being used inside the application itself to explain how the filesystem within the docker container looks. I do agree that for a production deployment this doesn't make sense in its current form. As compose files grow over time it's easy for those values to get out of sync and then we have a broken service.

I'm thinking the best course of action here would be to define an environment file and pass it into the compose. I'll take a look and see what I can do.

**Comment by lmnewton** [comment]
Addressed in PR #9 . There are some new steps in the README to cover the .env file, but this should keep configuration consistent and in a single place.
