### ISSUE TITLE
Developer mode hangs on large files when a search_term is present

### ISSUE THREAD

**Issue by AndyNewmanCRIBL** [lmnewton/log-exporter#4]
when running in dev mode, the application hangs when including a search term. This does not happen in production/ docker, just in fastapi

```bash
 READ_LOCATION=/var/log fastapi dev app/main.py 
```

```bash
curl --location 'http://localhost:8000/logs/syslog?page=1&search_term=kernel&lines_to_read=23&size=50' \
--data ''
```

```
INFO:     Application startup complete.
INFO:     2024-07-09 16:04:25,040 - Reading log /var/log/syslog. Returning last 2 lines.
INFO:     127.0.0.1:38590 - "GET /logs/syslog?page=1&lines_to_read=2&size=50 HTTP/1.1" 200 OK
INFO:     2024-07-09 16:04:35,080 - Reading log /var/log/syslog. Returning last 23 lines matching term 'kernel'.

```
the application hangs when searching for kernel, and does not respond

**Comment by lmnewton** [comment]
Thanks for finding this one.

Initially I suspected that this was just an issue with the small default buffer in dev mode, so I've adjusted that.

There is also a possibility that it has to do with the scrollback calculation as I've been able to trigger this behaviour with a different log. I've adjusted that as well and added tests using a file that I know triggers this case.

See linked PR #7 for changes.
